---



_target_: flwr.server.strategy.FedAvg
fraction_fit: 1.0           
min_fit_clients: 5        
fraction_evaluate: 1.0       
min_evaluate_clients: 5    
min_available_clients: 5
on_fit_config_fn: 
  _target_: server.get_on_fit_config
  config: ${config_fit}
  
   